### ISSUE TITLE
生成一份新的godwoken schemas的js代码

### ISSUE THREAD

**Issue by bitrocks** [bitrocks/godwoken-web3#11]
参考：https://github.com/xxuejie/moleculec-es

对应的mol代码：https://github.com/nervosnetwork/godwoken/tree/master/crates/types/schemas

**Comment by bitrocks** [comment]
参考lumos base: https://github.com/nervosnetwork/lumos/blob/develop/packages/base/package.json#L36

**Comment by classicalliu** [comment]
https://gist.github.com/classicalliu/e5af4cde78d0daff1c6f7e108a941884
